load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/dd_go_test:defs.bzl", "dd_go_test")

go_library(
    name = "teeconfig",
    srcs = ["teeconfig.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/config/teeconfig",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/config/model",
        "//pkg/util/log",
    ],
)

dd_go_test(
    name = "teeconfig_test",
    srcs = ["teeconfig_test.go"],
    embed = [":teeconfig"],
    deps = ["@com_github_stretchr_testify//assert"],
)
