load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "impl",
    srcs = [
        "impl.go",
        "providers.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/core/flare/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/api/api/def",
        "//comp/api/api/utils",
        "//comp/core/config",
        "//comp/core/flare/def",
        "//comp/core/flare/types",
        "//comp/core/ipc/def",
        "//comp/core/log/def",
        "//comp/core/workloadmeta/def",
        "//comp/def",
        "//comp/remote-config/rcclient/types",
        "//pkg/config/model",
        "//pkg/config/utils",
        "//pkg/util/option",
        "@//comp/core/flare/helpers",
        "@//pkg/flare",
    ],
)

go_test(
    name = "impl_test",
    srcs = ["impl_test.go"],
    embed = [":impl"],
    gotags = ["test"],
    deps = [
        "//comp/core/config",
        "//comp/core/flare/builder",
        "//comp/core/flare/def",
        "//comp/core/flare/types",
        "//comp/core/ipc/def",
        "//comp/core/ipc/mock",
        "//comp/core/log/def",
        "//comp/core/log/mock",
        "//comp/core/secrets/def",
        "//comp/core/secrets/mock",
        "//comp/core/tagger/def",
        "//comp/core/telemetry/fx-noop",
        "//comp/core/workloadmeta/def",
        "//comp/remote-config/rcclient/types",
        "//pkg/config/model",
        "//pkg/remoteconfig/state",
        "//pkg/util/fxutil",
        "//pkg/util/option",
        "@//comp/aggregator/demultiplexer/demultiplexerimpl",
        "@//comp/collector/collector",
        "@//comp/core/autodiscovery",
        "@//comp/core/autodiscovery/autodiscoveryimpl",
        "@//comp/core/autodiscovery/scheduler",
        "@//comp/core/flare/helpers",
        "@//comp/core/hostname/hostnameimpl",
        "@//comp/core/tagger/fx-mock",
        "@//comp/core/tagger/mock",
        "@//comp/core/workloadmeta/fx-mock",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_fx//:fx",
    ],
)
