load("@rules_go//go:def.bzl", "go_library")
load("//bazel/rules/dd_go_test:defs.bzl", "dd_go_test")

go_library(
    name = "compression",
    srcs = ["compression.go"],
    importpath = "github.com/DataDog/datadog-agent/pkg/util/compression",
    visibility = ["//visibility:public"],
)

dd_go_test(
    name = "compression_test",
    srcs = ["compression_test.go"],
    deps = [
        "//pkg/util/compression/impl-zstd",
        "//pkg/util/compression/impl-zstd-nocgo",
    ],
)
