load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "loclist",
    srcs = [
        "fix.go",
        "locations.go",
        "parse.go",
        "reader.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/dyninst/dwarf/loclist",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/dyninst/dwarf/dwarfutil",
        "//pkg/dyninst/ir",
    ],
)
