load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "jsonprune",
    srcs = [
        "doc.go",
        "prune.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/pkg/dyninst/jsonprune",
    visibility = ["//visibility:public"],
    deps = ["@com_github_go_json_experiment_json//jsontext"],
)
